use_frameworks!

target 'iDevice_Example' do
  pod 'iDevice', :path => '../'

  target 'iDevice_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
